name: Release Mode Unit Tests

on: [push, pull_request]

jobs:
 release-build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up build environment
      run: |
        sudo chmod +x ./ci-linux-setup.sh
        sudo ./ci-linux-setup.sh

    - name: Build executable
      run: |
        sudo chmod +x ./ci-build.sh
        sudo ./ci-build.sh

    - name: Run Unit Tests
      run: |
        sudo chmod +x ./ci-unit-test.sh
        ./ci-unit-test.sh
