name: Build Master Automated Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y meson cmake
        sudo apt-get install python3
        sudo apt-get install python-is-python3

    - name: Build executable
      run: |
        meson setup build
        meson compile -C build
        meson install -C build
    
    - name: Run Unit Tests
      run: |
        python ./unit_test/unit_test.py